services:
  go-backend:
    build: ./go-backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    restart: always
    volumes:
      - ./go-backend/data:/app/data
    

  sveltekit-frontend:
    build: ./sveltekit-frontend
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - go-backend
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  go-backend-data:
    driver: local