services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: samarth_sh
      POSTGRES_PASSWORD: 8Y0VfrsfgeIUOl5
      POSTGRES_DB: Password_Reset_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U samarth_sh -d Password_Reset_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-backend:
    container_name: go_backend
    build: ./go-backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./go-backend/.env

  sveltekit-frontend:
    container_name: sveltekit_frontend
    build: ./sveltekit-frontend
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - go-backend
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
